### ISSUE TITLE
Why do we have 2 versions of this?

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/TF-RED-Units#1]
We already had a Units repo setup with all the correct loadouts..completely done 100%.

**Comment by coachwn** [comment]
https://github.com/Task-Force-Red/Unit-Loadouts

**Comment by Jmaster9999** [comment]
These are not load-outs. This is the old SHG Units addon that scotty made. These are empty riflemen with custom class names for use with loadouts.
